### ISSUE TITLE
Připomínky k předobhajobě

### ISSUE THREAD

**Issue by YoungMasterGandalf** [jachymneumiprogramovat/rocnikovka2023-2024#3]
Note: priority levels --> 1 = HIGH, 2 = MED, 3 = LOW

* Výzkumná otázka (prio: 1)
Myslím, že by měla být formulována jasněji a hlavně by to měla být otázka, nikoli otázka a doplňková věta. Nějaké doplnění můžete říci slovně. Navrhuji něco ve stylu: "Pro jaké hodnoty úhlové rychlosti rotace míčku při dané počáteční rychlosti dochází při dopadu na tuhou podložku k odrazu, který směřuje zpět do poloroviny dopadu?" 
* Datum na titulním slidu (prio: 1)
* Teorie (prio: 2)
    - body 1 a 3 jsou totožné (říkají Vám totéž)
    - bod 4 je dosti vágní, šlo by formulovat přesněji, např. "Při kolmém dopadu míčku na povrch (volný pád) dochází ke zpětnému odrazu pro libovolnou zápornou hodnotu úhlové rychlosti rotace"
* Předpoklady (prio: 3)
    - uvádíte, co uvažujeme, uvedl bych i naopak co zanedbáváme, tedy např. místo "Deformuje se jen míček" dát "Uvažujeme pouze deformaci míčku, deformaci povrchu zanedbáváme" apod.
    - místo tam na to máte :)
 * Simulace (prio: 3)
     - mezery za čárkami
* Výsledky (prio: 1 - 2)
    - buď bych otočil implikaci (volba úhlu impikuje směr odrazové rychlosti), nebo bych tam dal ekvivalenci
    - vx1 a omega1 bych rozepsal slovně (kolega Bíža už si v tuto chvíli nebude pamatovat, co je co, na to vemte jed :))
* Cíl (prio: 3)
    - konrétnější jazyk ("Pro některé míčky a povchy..." --> "Pro různé typy míčků a materiály odrazových povrchů..." apod.)

**Comment by YoungMasterGandalf** [comment]
@jachymneumiprogramovat

**Comment by jachymneumiprogramovat** [comment]
Vše zapracováno! Jediné co jsem si upravil je znění otázky. Výraz "polorovina dopadu" mi přišel (například pro pana Bížu) zbytečně komplikující již tak složitou větu.
